import Head from 'next/head'
import Hero from '../comps/hero/Hero'


export default function Home() {
  return (
    <div>
      <Head>
        <title>48 Laws of Power</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    </div>
  )
}
