import Head from "next/head";
import Hero from "../comps/hero/Hero";
import LawSection from "../comps/lawSection/LawSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>48 Laws of Power</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />
      <LawSection />
    </div>
  );
}
